### PR TITLE
fix: fusion 13 `x86_x64` vmware tools location

### LINKED ISSUE #137: `vmware-iso`: "Couldn't find VMware tools for 'linux'!"
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue

Upgrading from VMWare Fusion 12 to Fusion 13 broke my current builds when installing VMWare Tools

#### Reproduction Steps

Using the vmware-iso builder, include the `tools_upload_flavor` directive and attempt to build a Linux machine. 

### Packer version

```
packer --version
1.9.1
```

### Simplified Packer Template

```
... snip ...
  # VM Configurations
  vm_name               = "base-vm"
  headless              = false
  shutdown_timeout      = "10m"
  snapshot_name         = "Base - ${formatdate("YYYY-MM-DD hh:mm", timestamp())}"

  # Bug in VMWare Fusion Pro 13?
  tools_upload_flavor   = "linux"
  # Begin Attempt to Fix 
  # tools_upload_path     = "/tmp"
  # tools_source_path     = "/Applications/VMware Fusion.app/Contents/Library/isoimages/x86_x64/linux.iso"
  # End Attempt to Fix 
... snip ...
```

### Operating system and Environment details

MacOS 13.4, Intel x64, VMWare Fusion Pro 13.0.2

### Log Fragments and crash.log files

```
2023/06/06 09:54:54 packer-builder-vmware-iso plugin: Detected VMware version: 13
2023/06/06 09:54:54 packer-builder-vmware-iso plugin: Testing against vmware driver *common.Fusion6Driver, Success: true
2023/06/06 09:54:54 [INFO] (telemetry) ending vmware-iso.base-<sensitive>
tools on-demand. However, to do this, you need to create a fake VM
of the proper type then click the 'install tools' option in the
VMware GUI.
==> Wait completed after 115 milliseconds 147 microseconds
2023/06/06 09:54:54 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2023/06/06 09:54:54 machine readable: base-<sensitive>.vmware-iso.base-<sensitive>,error []string{"Couldn't find VMware tools for 'linux'! VMware often downloads these\ntools on-demand. However, to do this, you need to create a fake VM\nof the proper type then click the 'install tools' option in the\nVMware GUI."}
tools on-demand. However, to do this, you need to create a fake VM
of the proper type then click the 'install tools' option in the
VMware GUI.
==> Builds finished but no artifacts were created.
2023/06/06 09:54:54 [INFO] (telemetry) Finalizing.
Build 'base-<sensitive>.vmware-iso.base-<sensitive>' errored after 115 milliseconds 91 microseconds: Couldn't find VMware tools for 'linux'! VMware often downloads these
tools on-demand. However, to do this, you need to create a fake VM
of the proper type then click the 'install tools' option in the
VMware GUI.

==> Wait completed after 115 milliseconds 147 microseconds
```

```
ls -l "/Applications/VMware Fusion.app/Contents/Library/isoimages/x86_x64/linux.iso"
-rw-r--r--@ 1 root  wheel  56272896 Apr 10 01:44 /Applications/VMware Fusion.app/Contents/Library/isoimages/x86_x64/linux.iso
```

I did try to make sure I was on the latest version of everything. Adding a requires block doesn't seem to help. Additionally, you can see in my comments that I tried manually specifying the path to the tools iso which also did not change the behavior.

```
packer init src/packer.pkr.hcl 
Installed plugin github.com/hashicorp/vmware v1.0.8 in "/usr/local/bin/github.com/hashicorp/vmware/packer-plugin-vmware_v1.0.8_x5.0_darwin_amd64"
```

```
packer build src/packer.pkr.hcl
base-<sensitive>.vmware-iso.base-<sensitive>: output will be in this color.

Build 'base-<sensitive>.vmware-iso.base-<sensitive>' errored after 201 milliseconds 154 microseconds: Couldn't find VMware tools for 'linux'! VMware often downloads these
tools on-demand. However, to do this, you need to create a fake VM
of the proper type then click the 'install tools' option in the
VMware GUI.

==> Wait completed after 201 milliseconds 229 microseconds

==> Some builds didn't complete successfully and had errors:
--> base-<sensitive>.vmware-iso.base-<sensitive>: Couldn't find VMware tools for 'linux'! VMware often downloads these
tools on-demand. However, to do this, you need to create a fake VM
of the proper type then click the 'install tools' option in the
VMware GUI.

==> Builds finished but no artifacts were created.
```

### PR DESCRIPTION
**Pull request by Stromweld**
Bug found in x86_64 directory as vmware fusion 13 has the vmware tools iso's in x86_x64 directory
Closes #137

### CODE REVIEW

**Comment by Stromweld** [comment]
I don't have a machine to test fusion 12 or less to verify if line [140](https://github.com/hashicorp/packer-plugin-vmware/blob/cb8e9b15bd8c4e9608257753355d8233ddc82a50/builder/vmware/common/driver_fusion6.go#L140) also needs updating.

**Comment by nywilken** [comment]
> I don't have a machine to test fusion 12 or less to verify if line [140](https://github.com/hashicorp/packer-plugin-vmware/blob/cb8e9b15bd8c4e9608257753355d8233ddc82a50/builder/vmware/common/driver_fusion6.go#L140) also needs updating.

@Stromweld apologies for the delayed response here. I've been traveling so just catching up. I have Fusion 12 and can confirm that we need some extra logic for fusion 12.

Channeling @tenthirtyam here, Fusion 12 is essentially unsupported as of March this year. Which seems to imply that maybe we should look to add the fusion driver or let Fusion 12 be for 1.0.8 and move to a new minor version for Fusion 13. Thoughts?

**Comment by Stromweld** [comment]
If it's unsupported that would make sense to me to potentially drop support and simplify the driver. I'd think since that would be a breaking change for all those with fusion 12 and below that it would warrant a major version increment. 1.x would be for 12 and below, where 2.x would then be for 13+.

**Comment by tenthirtyam** [comment]
lemme have a think this week and get back to you all.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by Stromweld** [comment]
Can we push this fix for x86 packer vmware builds and create an issue as a follow on to decide on what to do with fusion12 and earlier support?

**Comment by Stromweld** [comment]
@tenthirtyam any update?

**Comment by tenthirtyam** [comment]
@nywilken @Stromweld - while it could be considered a "breaking change" I recommend the following:

- Release v1.1.0 to address support for Fusion 13.x / Workstation 17.x and the change for the `isoimages`. 
- Previous versions, specifically v1.0.8 should be used for Fusion 12 / Workstation 16 which are no longer under general support. 
- Note in the CHANGELOG .mdand the GitHub release.
- Collaborate and review the scope to invest in a cleanup of the codebase and rev to v2.x.x.

**Comment by tenthirtyam** [comment]
@nywilken - This pull request can be superseded by https://github.com/hashicorp/packer-plugin-vmware/pull/139.

**Pull request closed without merging**
